[package]
name = "leptoast"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "*", features = ["csr"] }
reactive_stores = "*"

console_error_panic_hook = "*"

# tokio = { version = "*", features = ["time", "macros"] }
rayon = "*"
walkdir = "*"
